### ISSUE TITLE
pull production data fails in gitpod.

### ISSUE THREAD

**Issue by Sagargajare** [wagtail/wagtail.org#155]
`make pull-production-data`
`make pull-production-media`

This command fails to log in to Heroku on GITPOD.
![image](https://user-images.githubusercontent.com/56780589/164234440-44c5ff17-67e1-4be8-b9dc-0ef8642ddcaf.png)

for login, Heroku CLI provides a login link. If a user opens that link from their own browser (different IP address) it fails to verify due to an IP mismatch.

![image](https://user-images.githubusercontent.com/56780589/164234216-818c9519-90fb-4382-823e-0bfe7f9df618.png)

**Comment by zerolab** [comment]
@Sagargajare production data/media can only be pulled by people who have access.
Closin as non-issue
