### ISSUE TITLE
Account profile picture breaks when it is changed from default image

### ISSUE THREAD

**Issue by vossisboss** [wagtail/wagtail.org#174]
When I upload a new profile picture, the image doesn't change and it appears as broken image link throughout the rest of the website. I've tried using a smaller image and a different file format, but got the same results.

Here is a screenshot of what happens on the account profile page when I upload the photo:

![Screen Shot 2022-07-13 at 4 27 28 PM](https://user-images.githubusercontent.com/45881480/178828488-fb999512-2d31-492d-b1e2-fe880a70c10d.png)

And here are some screenshots of what is displayed instead of the photo in key places:

![Screen Shot 2022-07-13 at 4 27 35 PM](https://user-images.githubusercontent.com/45881480/178828573-784a0b9a-b09d-438d-bfd9-b801ee5328a8.png)

![Screen Shot 2022-07-13 at 4 28 10 PM](https://user-images.githubusercontent.com/45881480/178828601-a7127c12-1677-4059-beb5-b79049e6409a.png)

I tried to replicate the issue in my local installation of the website but it appears to be functioning properly in that instance. In the local environment, the image displays properly on the account profile page like this:

![Screen Shot 2022-07-13 at 4 30 19 PM](https://user-images.githubusercontent.com/45881480/178828792-0695b4bf-fb33-42ec-87e7-0ce337294d03.png)

So it appears that the issue is only in the production environment yet I'm not sure where to check for errors related to images. Would love to hear any suggestions to help track this down.

**Comment by zerolab** [comment]
Can you replicate this with bakerydemo? or a simple `wagtail start` instance?

**Comment by vossisboss** [comment]
I'll give it a try when @zerolab and see what happens. I assume you would roll back the Wagtail version to the one we're currently using on production?

**Comment by zerolab** [comment]
Yes. looks like prod is on 2.16. So it may be an issue with the instance, rather than Wagtail 2.16 as we would've had bug reports by now 🤔

**Comment by vossisboss** [comment]
@zerolab So rolling back the Bakery to 2.16 is more trouble than it's worth to test this (would have to undo things related to wagtail.admin.panels, etc.).

Did a fresh `wagtail start` sit and the image uploaded fine.

![Screen Shot 2022-07-14 at 9 19 20 AM](https://user-images.githubusercontent.com/45881480/178992025-ab563161-46bc-4730-8501-edeeb47cb8e2.png)

So it looks like this is an issue with the instance. I suppose now is as good as time as any to see if I have the permissions to access our Heroku logs...

**Comment by vossisboss** [comment]
@zerolab I do have access to our logs. There were no obvious errors when I tried adding my image again and when I replicated the issue by creating a new user. Granted, I'm not as familiar with the activity on our production app, so if the error is a more subtle one, I'm not likely to spot it right away.

![Screen Shot 2022-07-14 at 10 14 58 AM](https://user-images.githubusercontent.com/45881480/179010525-556dd5c6-2291-4dfd-9de6-a471c6b8e391.png)

I looked in the inspector and it appears that the image file exists. It's just not being loaded and I'm not sure why.

![Screen Shot 2022-07-14 at 10 41 13 AM](https://user-images.githubusercontent.com/45881480/179011032-d3972e45-d46f-4d88-82b1-8da17859119c.png)

The only other places I can think to check is to confirm whether the file is actually appearing in our AWS storage bucket and/or whether the issue can be replicated on our dev instance. I don't currently have access to either of those. Should I pursue access? Or team up with someone who has it?

**Comment by vossisboss** [comment]
Ah. I'll file a ticket in Codebase then and see if someone has any insights on that front. I'll close this out after I hear back. Thanks @zerolab !

**Comment by RealOrangeOne** [comment]
Yep definitely an issue with the hosting infrastructure, as opposed to something in the application itself.

Will keep this issue open to track, but moving discussion internal.

**Comment by RealOrangeOne** [comment]
The problem was that `avatar_images/` wasn't accessible to the world, which is where Wagtail stores its avatar images:

https://github.com/wagtail/wagtail/blob/716bf92c2dc2da2aca5e8f5aa6768b5b087cd4b0/wagtail/users/models.py#L10-L17

Ideally avatars would reuse the rendition logic, which would not only resize them, but also serve them from a location which was already accessible. See also https://github.com/wagtail/wagtail/issues/755

I've deployed a configuration change, and tested the avatar images now appear:

![image](https://user-images.githubusercontent.com/6527489/179506157-7b874d1c-ed88-4b11-80c5-516028f94cb7.png)

**Comment by vossisboss** [comment]
Thank you for tracking this down @RealOrangeOne !
