### ISSUE TITLE
CORS: Nightly releases page uses old wagtail.io URL

### ISSUE THREAD

**Issue by th3hamm0r** [wagtail/wagtail.org#223]
https://releases.wagtail.org/nightly/index.html currently tries to fetch https://releases.wagtail.io/nightly/latest.json, which fails due to CORS.
Until it is fixed I'm using https://releases.wagtail.io/nightly/index.html

**Comment by thibaudcolas** [comment]
Fixed :) Thanks again for reporting this @th3hamm0r, though in the future you might have better luck on https://github.com/wagtail/wagtail. Issues on this repository aren’t triaged that often.

**Comment by robmoorman** [comment]
Back to cors errors it is @thibaudcolas could we re-open this (and fit it ;)) see https://github.com/wagtail/wagtail/issues/9753

**Comment by lb-** [comment]
@robmoorman I have opted to move the Wagtail issue to this repo instead https://github.com/wagtail/wagtail.org/issues/356
