### ISSUE TITLE
Wagtail 3 compatibility

### ISSUE THREAD

**Issue by nickmoreton** [wagtail/wagtail.org#263]
Hello

There's a Wagtail 3 upgrade PR here: https://github.com/wagtail/wagtail.org/pull/159

Can it be considered please?

I am also putting a Wagtail 4 upgrade together which will rely on this upgrade. Thanks

**Comment by zerolab** [comment]
Thanks @nickmoreton, @bcdickinson will be looking at the Wagtail 4 upgrade and incorporated bits of #159.
Please focus your efforts on other projects.
