### ISSUE TITLE
add ability to search for the Author name in the snippet chooser

### ISSUE THREAD

**Issue by lb-** [wagtail/wagtail.org#267]
When writing a draft post this week I found that the Author searching was not enabled for the snippet chooser. 

There are now close to three pages of authors and it would be nice to be able to search. 

This should be a small change and can use the DB index 

https://github.com/wagtail/wagtail.org/blob/bde551d147c8eab660fc417d831c94176783854a/wagtailio/blog/models.py#L60

https://docs.wagtail.org/en/stable/topics/snippets.html#making-snippets-searchable

**Comment by zerolab** [comment]
Will be released in via `next` sometime next week if all goes well
