### ISSUE TITLE
Create downloadable resource pack

### ISSUE THREAD

**Issue by kaedroho** [wagtail/wagtail.org#3]
(originally posted by @zerolab)

From the Wagtail slack:

> maartenkling [8:50 AM] 
> There should be a official logopack somewhere on wagtail.io

This is a good idea. The pack should contain the Wagtail logo, "made with Wagtail" badge and variations. Maybe even a short brand styleguide.

**Comment by zerolab** [comment]
+ 💯 for this.

Found https://wagtail.io/wagtail-badges/ which is only linked from the bottom of the about page. A start, but needs more and definitely should be more visible

**Comment by thibaudcolas** [comment]
@vossisboss what do you think of this?

**Comment by vossisboss** [comment]
We now have the repository https://github.com/wagtail/brand as a resource for people to use in getting our logo packs and we have updated the FAQs page with a link to the repo.
