### ISSUE TITLE
Footer – At larger font sizes, content sits very closely and runs into each other in the footer

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail.org#316]
Suggested fix: Make sure spacing remains consistent at larger font sizes

**Comment by Julietadeboye** [comment]
Hi, @thibaudcolas please can you provide a screenshot so I can verify that I'm recreating the right issue? Thanks

**Comment by Aarthy153** [comment]
Hi, I am looking forward to fixing this issue. Can u assign it to me?

**Comment by thibaudcolas** [comment]
This appears to have been fixed.
