### ISSUE TITLE
Performance: serve images in next-gen formats

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail.org#328]
As per recommendation from Google Lighthouse. I believe this site uses Cloudflare, be nice to check if we can enable Cloudflare Polish first, and if not make the necessary code changes so all images are rendered as both WebP and a fallback format.

**Comment by thibaudcolas** [comment]
@tomusher yes please!

**Comment by tomusher** [comment]
OK that's enabled. Note that it only chooses WebP if 
"... the Accept header from the browser includes WebP, and the **compressed image is significantly smaller** than the lossy or lossless compression:"
(https://developers.cloudflare.com/images/polish/compression/#webp)

I've also switch Polish to use lossy compression which will increase the number of images that use WebP, and generally reduce image weight, but if you find this is causing issues we can switch back to lossless.

**Comment by thibaudcolas** [comment]
Looking excellent! All homepage images seem to be served as WebP currently. Quality seems acceptable to me on a low-DPI monitor.

Debugbear is happy too:

![wagtail.org homepage weight](https://user-images.githubusercontent.com/877585/201891266-8b7e4bcd-4327-4741-8cdd-f326a66fb7e4.png)
