### ISSUE TITLE
Performance: Enable text compression

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail.org#329]
Recommendation from Google Lighthouse. This is text compression for the main HTML document response for a given page.

If this site uses Cloudflare it’d be nice if this could be enabled there, as some of our pages run into the hundreds of kilobytes without compression. If not possible, we should investigate the Django middleware that does this, if we can work around the security complications.

**Comment by zerolab** [comment]
My preference would be for this to happen in Cloudflare.

https://docs.djangoproject.com/en/3.2/ref/middleware/#django.middleware.gzip.GZipMiddleware

**Comment by tomusher** [comment]
Brotli compression is enabled through Cloudflare at https://next.wagtail.org
