### ISSUE TITLE
Performance: browser caching for images

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail.org#330]
Currently it seems our images are served without a `cache-control` header. We should set this up, with cache-busting in the URL generation, so we can leverage client-side caching.

For example, our stylesheets are served with:

```
Cache-Control: max-age=315360000, public, immutable
```

The vast majority of images on the site should rarely change, so would greatly benefit from further caching.

**Comment by tomusher** [comment]
I have added a cache-control header to media assets for 1 year - as we have `AWS_S3_FILE_OVERWRITE` set to False, the assets at these URLs should never change.

**Comment by zerolab** [comment]
LGTM
