### ISSUE TITLE
Small typo - Wagtail Name

### ISSUE THREAD

**Issue by lb-** [wagtail/wagtail.org#336]
![Screenshot_20221115-051550](https://user-images.githubusercontent.com/1396140/201746489-e7eb7dce-763b-49d5-bed6-3015de5efc5b.png)

https://wagtail.org/about-wagtail/

> Where did the Wagtail Name come from?

Should be 

> Where did the Wagtail name come from?

Name is not a proper noun in this context I think.

**Comment by zerolab** [comment]
Should be fixed now. @lb- I believe you have access to make such edits, should you wish to ;)

**Comment by lb-** [comment]
Oh yeah. Didn't think of that haha. Thanks
