### ISSUE TITLE
Featured label needed for the featured blogs on the main Blog page

### ISSUE THREAD

**Issue by vossisboss** [wagtail/wagtail.org#351]
Some users have commented that the Featured blogs at [wagtail.org/blog] (https://www.wagtail.org/blog) are confusing because the dates are out of order. We need to keep the dates but add a text label that indicates to visitors that these blog posts are "Featured" and are not necessarily appearing in chronological order.

**Comment by hgupta12** [comment]
Hello @vossisboss , I can work on this issue. Can you assign it to me?

**Comment by vossisboss** [comment]
It's been assigned @hgupta12 !

**Comment by tajbaba999** [comment]
Hey, @vossisboss have you working on this issue?
Hello @vossisboss man can I work on this issue?

**Comment by adviksinghania** [comment]
Hey @vossisboss , where should the final changes be reflected, like for example, is this okay?


![image](https://user-images.githubusercontent.com/72959852/211999902-26a618f6-5d06-4e6f-acfb-10d8baebcf24.png)

**Comment by nishantn31** [comment]
@vossisboss Is this issue still open? If yes, I would like to work on this.

**Comment by thibaudcolas** [comment]
@nishantn31 go for it

**Comment by nishantn31** [comment]
Hi @thibaudcolas I have set up Wagtail cms on my local environment. However I can't find a way to designate a blog as featured. Can you please guide me or refer any documentation related to that.

**Comment by thibaudcolas** [comment]
@nishantn31 what have you tried so far? I’m confused on how you came up with a pull request without identifying this.

**Comment by nishantn31** [comment]
@thibaudcolas I tried checking the code and exploring Admin UI and figured out how can we make the blog featured. 
@cnk also suggested some points on my query on Slack and it helped me resolve the issue.
