### ISSUE TITLE
Double scroll bars in blog post

### ISSUE THREAD

**Issue by zerolab** [wagtail/wagtail.org#386]
https://wagtail.org/blog/wagtailers-flocked-to-scotland-for-djangocon-europe-2023/

![Screenshot 2023-06-08 at 09 50 55](https://github.com/wagtail/wagtail.org/assets/31622/f2a6dbeb-eb9f-483c-b3ab-13bbebd81066)

**Comment by nicklee** [comment]
This was fixed as part of the Dark mode work 👍
