### ISSUE TITLE
Text disappears when hovering on "Sponsor Wagtail" and "Contribute code" in the footer in light mode

### ISSUE THREAD

**Issue by laymonage** [wagtail/wagtail.org#405]
https://github.com/wagtail/wagtail.org/assets/6379424/ce16e27d-7390-4ef7-88df-bbba738a6eb2

Not an issue in dark mode.

**Comment by MugoBrian** [comment]
Is the wagtai.org site or which site? @laymonage

**Comment by laymonage** [comment]
We don't assign issues outside of the core team members, if you'd like to work on this then go ahead and make a pull request :)

**Comment by MugoBrian** [comment]
Ooh, thank you. I will

**Comment by khushishikhu** [comment]
@laymonage I am interested in working on this issue. Can I move ahead with this?

**Comment by laymonage** [comment]
@khushishikhu yep, though it looks like @MugoBrian is interested as well. There's no PR yet so anyone's free to contribute.

**Comment by khushishikhu** [comment]
> @khushishikhu yep, though it looks like @MugoBrian is interested as well. There's no PR yet so anyone's free to contribute.

I need some guidance how to run this project on windows 11,  I have downloaded docker but troubling to start this application

**Comment by MugoBrian** [comment]
> @khushishikhu yep, though it looks like @MugoBrian is interested as well. There's no PR yet so anyone's free to contribute.

I am hitting a blocker in setting up the repository locally that's why there's no PR on the issue.

**Comment by thibaudcolas** [comment]
Please keep on topic in GitHub – if you want to repot setup issues you’re having and ask for help that’s fine, but either create a new issue / Discussions thread about it. We want to keep conversation here about this specific issue.

**Comment by nicklee** [comment]
This has been fixed via https://github.com/wagtail/wagtail.org/pull/425

**Comment by MugoBrian** [comment]
@nicklee . With regard to PR #425. I noticed it's only fixing issue #409 and not issue #405. Is there something I am missing?
