### ISSUE TITLE
Dark mode feature on main web page 

### ISSUE THREAD

**Issue by martcpp** [wagtail/wagtail.org#407]
I am new to wagtails I love the project but I noticed some issue which I will like to work on
The dark mode feature on the main web page is at the footer , I believe it will be more effective being bat the top of the website.
Reason is that I don't want to use dark mode after I finish reading the doc. But want to active dark mode before reading.
# The current position

![Screenshot_20230924-112329](https://github.com/wagtail/wagtail.org/assets/103220475/58ccecc3-af2e-4290-8bfe-72fb27188578)
 # Propose position 
- any where close to the search button
![Screenshot_20230924-112206](https://github.com/wagtail/wagtail.org/assets/103220475/2328ea57-b1cb-462a-a029-f4be2fd8665d)

```[tasklist]
### Tasks
```

```[tasklist]
### ui/ux
```

**Comment by martcpp** [comment]
@tomdyson @tomusher pls can i start working on this

**Comment by thibaudcolas** [comment]
@martcpp  Please avoid pinging other people about issues. We put this in the footer on purpose – the theme follows your OS theme by default, so it felt reasonable to us that the control didn’t have to be immediately available.
