### ISSUE TITLE
Highlight social media icons in footer using hover effect

### ISSUE THREAD

**Issue by HarshithaPerumalla** [wagtail/wagtail.org#408]
### Issue Summary
I seen hovering effect on all the buttons and icons in footer like sponsor wagtail, contribute code buttons and sign up button. but I couldn't see the hovering effect while moving and clicking social media icons.

### Steps to Reproduce

to fix bug: add hovering effect on social media icons while moving and clicking on the icons.

### Technical details

-   Python version: Run `python --version`.
-   Django version: Look in your requirements.txt, or run `pip show django | grep Version`.
-   Wagtail version: Look at the bottom of the Settings menu in the Wagtail admin, or run `pip show wagtail | grep Version:`.
-   Browser version: You can use https://www.whatsmybrowser.org/ to find this out.

https://github.com/wagtail/wagtail/assets/94059890/a39d4a3c-10fb-42a1-8b2e-8a24550c3452

**Comment by HarshithaPerumalla** [comment]
Can you asign this task to me . so that I can start working on it
Thankyou

**Comment by HarshithaPerumalla** [comment]
Is it already resolved or Can I work on it?

**Comment by lb-** [comment]
@HarshithaPerumalla  - we do not normally assign issues, it's also not been looked at by anyone that manages this website (please give it a few days at least). I think it's worth cleaning up though but I am not sure in the exact desired styling but if you have a good idea, go for it and raise a PR.

**Comment by HarshithaPerumalla** [comment]
Okay. I'm working on it.

**Comment by thibaudcolas** [comment]
Thanks for investigating this @HarshithaPerumalla! That’d be a great contribution if you’re up for it.

Make sure to:

- Pick a color that works well against the background. Looks like we could pick the same hover color as other links in the footer perhaps?
- Make this work both for the site’s light and dark themes.

**Comment by HarshithaPerumalla** [comment]
Yeah I'm planning to choose existing hover color and also I will make sure it works for dark mode as well.

**Comment by thibaudcolas** [comment]
Fixed in #441
