### ISSUE TITLE
Reduce size of large headings

### ISSUE THREAD

**Issue by benenright** [wagtail/wagtail.org#412]
To better accommodate longer headlines and feel a bit less shouty, can we reduce the font-size and line-height of the large headlines to 4rem and 4.4rem on desktop:

![image](https://github.com/wagtail/wagtail.org/assets/4907819/b4ceae28-c301-49b4-b388-9a690ce65e54)

<img width="1390" alt="image" src="https://github.com/wagtail/wagtail.org/assets/4907819/0ce1d51f-9169-45ec-8a88-055896379b8a">

<img width="1368" alt="image" src="https://github.com/wagtail/wagtail.org/assets/4907819/d997072f-36d5-4639-84b4-e81ea5a8edfb">

**Comment by benenright** [comment]
Similarly, reduce H2's within the blog page body on desktop.

![image](https://github.com/wagtail/wagtail.org/assets/4907819/23da6582-6855-4d87-a053-7a5ec1abed77)

<img width="866" alt="image" src="https://github.com/wagtail/wagtail.org/assets/4907819/aaef4ce1-7153-4246-98ba-977e7b238ec8">

**Comment by oly-baby** [comment]
hello, can i work on this

**Comment by thibaudcolas** [comment]
@oly-baby 👋 thanks for your interest in this! You can go ahead. No need to ask for permission, everything on our issue tracker is there for the taking unless someone else has already been working on it.

Please take a moment to understand the task at hand, make sure you can reproduce the current state of things on your copy of the project, and then implement the desired changes as per what the issue describes.

**Comment by oly-baby** [comment]
Alright 👍

**Comment by OsafAliSayed** [comment]
Is this issue closed or still needs working?

**Comment by benenright** [comment]
Hi @chris-lawton 

Here are the values I'd like to update to (just on desktop for now):

### h1, .heading-one 
![image](https://github.com/wagtail/wagtail.org/assets/4907819/01327b0a-f32d-4afd-a9c4-ec9a2f0a4b92)

### .intro-big
![image](https://github.com/wagtail/wagtail.org/assets/4907819/ac984f70-27e6-4f61-bd72-1427be478139)

### h2 
![image](https://github.com/wagtail/wagtail.org/assets/4907819/1b982eb5-99f4-42ee-a676-709e08808eff)

**Comment by benenright** [comment]
Sorry, i got the H2 one wrong above. Should also be:
![image](https://github.com/wagtail/wagtail.org/assets/4907819/617581e9-6c90-4459-8093-c0b195854dfe)
(34px)

**Comment by thibaudcolas** [comment]
Fixed in #472.
