### ISSUE TITLE
Repeatation of word

### ISSUE THREAD

**Issue by oly-baby** [wagtail/wagtail.org#424]
In packages in Resources page, of was repeated twice in wagtail-readinglevel [LINK TO THE PACKAGE PAGE](https://wagtail.org/packages/)
![issue](https://github.com/wagtail/wagtail.org/assets/131376909/81956206-7bf4-4c47-b516-eb02819dfdbe)

**Comment by oly-baby** [comment]
@thibaudcolas Good day,

Please i found this issue, can i work on it

**Comment by zerolab** [comment]
@oly-baby https://wagtail.org/packages/ is powered by the https://djangopackages.org API. That description comes from https://djangopackages.org/packages/p/wagtail-readinglevel/ and it looks like it has been deprecated. You could check how descriptions can be updated on djangopackages, or even better, how to remove that package from the Wagtail comparison grids on djangopackages.com

**Comment by oly-baby** [comment]
Thank you so much, I will check it out

**Comment by oly-baby** [comment]
@zerolab 
so this issues is from django packages and not from wagtail website, which means it is not an issue in wagtail website.

**Comment by zerolab** [comment]
That is correct. I will close this issue on that basis. But thank you very much for flagging it.

**Comment by oly-baby** [comment]
you are welcome
