### ISSUE TITLE
Disappearing Text on Hover for 'Sponsor This' in Light Mode on the Wagtail Roadmap Page

### ISSUE THREAD

**Issue by MugoBrian** [wagtail/wagtail.org#428]
Description:

On the Wagtail Roadmap Page, there's a concerning accessibility issue that needs attention. When you hover over the "Sponsor This" link in the milestone card while in light mode, the text disappears. 
See the screen recording below.
[Screencast from 21-10-2023 04:37:24 ALASIRI.webm](https://github.com/wagtail/wagtail.org/assets/49617104/c67c8201-8d5d-46d4-9294-873c7990b4cb)

This is an accessibility issue because:

1. Disappearing text on hover affects users with low vision or color blindness.
2. It creates confusion for keyboard users who rely on clear visual feedback.
3. Non-compliance with web accessibility standards.

**Comment by thibaudcolas** [comment]
Fixed in #429
