### ISSUE TITLE
adding new page error

### ISSUE THREAD

**Issue by parsavandy** [wagtail/wagtail.org#469]
when i attempt to create any new pages it will give me this error
`WebpackManifestNotFound at /mypage/ Manifest file not found. Looked for it at /app/wagtailio/static_compiled/manifest.json. Either your settings are wrong or you still need to generate the file. Request Method:	GET Request URL:	http://0.0.0.0:8000/mypage/ Django Version:	4.2.8 Exception Type:	WebpackManifestNotFound Exception Value: Manifest file not found. Looked for it at /app/wagtailio/static_compiled/manifest.json. Either your settings are wrong or you still need to generate the file. Exception Location:	/venv/lib/python3.11/site-packages/manifest_loader/utils.py, line 76, in _get_manifest Raised during:	wagtail.views.serve Python Executable:	/venv/bin/python Python Version:	3.11.8 Python Path: ['/venv/bin', '/app', '/usr/local/lib/python311.zip', '/usr/local/lib/python3.11', '/usr/local/lib/python3.11/lib-dynload', '/venv/lib/python3.11/site-packages'] Server time:	Sun, 24 Mar 2024 17:15:02 +0000`

altho there is no static_compiled folder :|

**Comment by Stormheg** [comment]
Hello @parsavandy 

Did you read this section in the README?

https://github.com/wagtail/wagtail.org/blob/468ccd44a65dee3fa9f574bbdc72689fc3a220e1/README.md?plain=1#L111-L117

It explains how to build the frontend assets, which the error indicates is missing

I'll go ahead and close this now.
