### ISSUE TITLE
Sector Selector Doesn't Work in Showcase page type

### ISSUE THREAD

**Issue by vossisboss** [wagtail/wagtail.org#471]
I created a Showcase page and published it because the Preview doesn't allow me to see all the pages. When I did this, I discovered that there was a bug in the Sector selector in Firefox. The sectors do not appear in the selector and the dropdown action doesn't occur like it is supposed to. Here is a screenshot:

![Screenshot 2024-05-08 at 3 31 27 PM](https://github.com/wagtail/wagtail.org/assets/45881480/41ba4629-5e04-43bc-968b-14b1cdaf62d6)

I was able to reproduce the bug in Chrome as well but in Chrome, the drop down doesn't even appear:

![Screenshot 2024-05-08 at 3 42 52 PM](https://github.com/wagtail/wagtail.org/assets/45881480/e5e17477-0f4f-4867-97b8-1c8c2d65cae4)

There were no relevant errors in the console as far as I could observe.

**Comment by thibaudcolas** [comment]
Fixed in 42c68070cc45f99c73c64a8d43cb02a98bc65506, sorry about that!
