### ISSUE TITLE
Retina images

### ISSUE THREAD

**Issue by kaedroho** [wagtail/wagtail.org#6]
(originally posted by @tomdyson)

eg. the screenshots for the feature list on the home page, user-uploaded images in blog posts

**Comment by jckpn** [comment]
I've done some new screenshots for the [features page](https://wagtail.io/features/) if it's of any help:

[features.zip](https://github.com/wagtail/wagtail.io/files/3956721/features.zip)

Note that they omit the app header as this is added through the pages styling, although currently the screenshots still include them which looks a little [funny](https://user-images.githubusercontent.com/14837124/70728247-fa98b380-1cf8-11ea-873c-df3ddccdba95.png) sometimes

**Comment by thibaudcolas** [comment]
The homepage screenshots seem to be rendition-ed at 2x their displayed desktop width on the upcoming redesign, so will close this now.
