### ISSUE TITLE
Reader mode doesn't work on the blog

### ISSUE THREAD

**Issue by kaedroho** [wagtail/wagtail.org#76]
We should use semantic HTML on the blog so that browsers and services like Pocket can provide a reader mode.

**Comment by thibaudcolas** [comment]
Testing on our upcoming redesign Reader mode seems to work as expected for blog posts (tested in Safari). I get the text, heading, links, YouTube embeds, images. I’ll close this now, would be nice to keep improving this in the future if there are specific types of formatting that don’t show up.
