### ISSUE TITLE
Links within blog posts aren't clickable - Mobile only

### ISSUE THREAD

**Issue by nicklee** [wagtail/wagtail.org#77]
Issue:
When browsing https://wagtail.io/blog/documentation-sprint-2021/ on mobile, the link to the sprint form isn't clickable.

Reason:
The mobile blog index menu is overlaying the article, meaning you click items in this instead of the blog article

![Image from iOS](https://user-images.githubusercontent.com/298766/99701567-862fce00-2a8c-11eb-9cde-3359085ff425.png)
![Image from iOS (2)](https://user-images.githubusercontent.com/298766/99701573-892abe80-2a8c-11eb-8ae7-c58198d74ca9.jpg)
![Image from iOS (1)](https://user-images.githubusercontent.com/298766/99701576-8a5beb80-2a8c-11eb-90fe-2685356a0b83.jpg)

**Comment by nicklee** [comment]
Fix:
we need to add `pointer-events: none` to `.blog-listing__link` when body doesn’t have `sidebar-open` on the mobile breakpoint

**Comment by thibaudcolas** [comment]
I assume this will no longer be relevant with our upcoming launch of the new-and-updated design and content, so will close this now.
