### ISSUE TITLE
Wagtail statistics for site

### ISSUE THREAD

**Issue by kaedroho** [wagtail/wagtail.org#9]
(originally posted by @heymonkeyriot)

In the footer of the site there's an idea to introduce statistics about Wagtail
e.g.

>  3,509 Stargazers
>  659 forks
>  58 closed issues in last 30 days
>  91 commits in the last 30 days
>  160 contributors

**Comment by thibaudcolas** [comment]
I assume this will no longer be relevant with our upcoming launch of the new-and-updated design and content, so will close this now.

The redesign explicitly includes a counter of stars, and contributors.
